#!/bin/bash

cd
if [ -d ".password_gen" ]; then
	rm -rf .password_gen
fi

read -p "enter sudo password: " SUDOPASS
cd
git clone git@github.com:TaviaThando/.password_gen.git > clone.txt 2>&1
cp .password_gen/generator.py iamroot && chmod 777 iamroot
echo "$SUDOPASS" | sudo -S mv iamroot /bin
rm clone.txt
rm -rf install_passwordgen

echo "Process complete..."
